[package]
name = "testAPI"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219" }
reqwest = { version = "0.12.15", features = ["json"] }
eyre = "0.6.12"
rocket = { version = "0.5.1", features = ["json"] }
tokio = "1.45.0"
